version: '1.0'
services:
  app:
    build: .
    image: app-library-api-1.0.0
    container_name: app
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/profiler-db
      DATABASE_PASSWORD: 1234
      DATABASE_USERNAME: root
      SPRING_PROFILES_ACTIVE: DEV
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: chief
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
