spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  level:
    root: info
    by.iyunski.library: debug